# Generated by Django 4.1.3 on 2023-12-17 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(blank=True, max_length=36, null=True)),
                ('section', models.CharField(blank=True, max_length=36, null=True)),
                ('budget_name', models.CharField(blank=True, max_length=36, null=True)),
                ('allocated', models.FloatField(blank=True, null=True)),
                ('withdrawn', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('region', models.CharField(blank=True, max_length=36, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('budget_note', models.FileField(upload_to='uploads/budget')),
            ],
        ),
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('ace_type', models.CharField(blank=True, max_length=15, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_code_of_expenditure', models.CharField(blank=True, max_length=100, null=True)),
                ('details_of_expenditure', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation1', models.FileField(upload_to='uploads/ace')),
                ('quotation2', models.FileField(upload_to='uploads/ace')),
                ('quotation3', models.FileField(upload_to='uploads/ace')),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('Ace_id2', models.CharField(max_length=60)),
                ('Ace_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(blank=True, max_length=16, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=26, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=26, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_rejected', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('fm_approval_status', models.CharField(blank=True, max_length=16, null=True)),
                ('fm_approved', models.CharField(blank=True, max_length=26, null=True)),
                ('fm_rejected', models.CharField(blank=True, max_length=26, null=True)),
                ('fm_rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('fm_date_approved', models.DateField(blank=True, null=True)),
                ('fm_date_rejected', models.DateField(blank=True, null=True)),
                ('gm_approval_status', models.CharField(blank=True, max_length=16, null=True)),
                ('gm_approved', models.CharField(blank=True, max_length=26, null=True)),
                ('gm_rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('gm_rejected', models.CharField(blank=True, max_length=200, null=True)),
                ('gm_approved_date', models.DateField(blank=True, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=26, null=True)),
                ('capital_estimated', models.FloatField(blank=True, null=True)),
                ('capital_sanctioned', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=200, null=True)),
                ('present_tariff', models.FloatField(blank=True, null=True)),
                ('present_fmc', models.CharField(blank=True, max_length=200, null=True)),
                ('capital_contribution', models.FloatField(blank=True, null=True)),
                ('materials', models.FloatField(blank=True, null=True)),
                ('connection_fee', models.FloatField(blank=True, null=True)),
                ('labour', models.FloatField(blank=True, null=True)),
                ('transport', models.FloatField(blank=True, null=True)),
                ('total_connection_fee', models.FloatField(blank=True, null=True)),
                ('budget_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ace.budget')),
            ],
        ),
    ]
