# Generated by Django 4.1.3 on 2024-01-18 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_code_of_expenditure', models.CharField(blank=True, max_length=100, null=True)),
                ('details_of_expenditure', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('quotation1', models.FileField(upload_to='uploads/ace')),
                ('quotation2', models.FileField(upload_to='uploads/ace')),
                ('quotation3', models.FileField(upload_to='uploads/ace')),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('Ace_id2', models.CharField(max_length=60)),
                ('Ace_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.CharField(blank=True, max_length=120, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=56, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=56, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_rejected', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('section_head', models.CharField(max_length=30, null=True)),
                ('section_head_approval_status', models.CharField(blank=True, max_length=40, null=True)),
                ('section_head_rejection_reason', models.CharField(blank=True, max_length=35, null=True)),
                ('section_head_approval_date', models.DateField(blank=True, null=True)),
                ('accounting_officer', models.CharField(max_length=30, null=True)),
                ('accounting_officer_approval_status', models.CharField(blank=True, max_length=40, null=True)),
                ('accounting_officer_rejection_reason', models.CharField(blank=True, max_length=4000, null=True)),
                ('accounting_officer_approval_date', models.DateField(blank=True, null=True)),
                ('finance_manager', models.CharField(blank=True, max_length=60, null=True)),
                ('fm_approval_status', models.CharField(blank=True, max_length=40, null=True)),
                ('fm_rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('fm_date_approved', models.DateField(blank=True, null=True)),
                ('fm_date_rejected', models.DateField(blank=True, null=True)),
                ('general_manager', models.CharField(blank=True, max_length=30, null=True)),
                ('gm_approval_status', models.CharField(blank=True, max_length=16, null=True)),
                ('gm_approved', models.CharField(blank=True, max_length=26, null=True)),
                ('gm_rejection_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('gm_approved_date', models.DateField(blank=True, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=26, null=True)),
                ('capital_estimated', models.FloatField(blank=True, null=True)),
                ('capital_sanctioned', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('classification', models.CharField(blank=True, max_length=200, null=True)),
                ('present_tariff', models.FloatField(blank=True, null=True)),
                ('present_fmc', models.CharField(blank=True, max_length=200, null=True)),
                ('capital_contribution', models.FloatField(blank=True, null=True)),
                ('materials', models.FloatField(blank=True, null=True)),
                ('connection_fee', models.FloatField(blank=True, null=True)),
                ('labour', models.FloatField(blank=True, null=True)),
                ('transport', models.FloatField(blank=True, null=True)),
                ('total_connection_fee', models.FloatField(blank=True, null=True)),
                ('designation', models.CharField(max_length=70, null=True)),
                ('approval_code', models.IntegerField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.CharField(blank=True, max_length=36, null=True)),
                ('section', models.CharField(blank=True, max_length=36, null=True)),
                ('budget_name', models.CharField(blank=True, max_length=36, null=True)),
                ('allocated', models.FloatField(blank=True, null=True)),
                ('awaiting_sanctioning', models.FloatField(blank=True, default=0, null=True)),
                ('withdrawn', models.FloatField(blank=True, default=0, null=True)),
                ('to_be_withdrawn', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('period', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('region', models.CharField(blank=True, max_length=36, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('budget_note', models.FileField(upload_to='uploads/budget')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('details_of_expenditure', models.CharField(blank=True, max_length=120, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=120, null=True)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.FloatField(blank=True, max_length=120, null=True)),
                ('ace2', models.CharField(blank=True, max_length=120, null=True)),
                ('Ace_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ace.ace')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ace.budget')),
            ],
        ),
        migrations.AddField(
            model_name='ace',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ace.budget'),
        ),
    ]
