# Generated by Django 4.1.3 on 2024-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
