# Generated by Django 4.1.3 on 2023-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ace',
            name='ace_type',
        ),
        migrations.AddField(
            model_name='ace',
            name='designation',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
