# Generated by Django 4.1.3 on 2024-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0002_alter_budget_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='section_head_rejection_reason',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
