# Generated by Django 4.1.3 on 2023-12-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0002_remove_ace_ace_type_ace_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ace',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='region',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
