# Generated by Django 4.1.3 on 2023-12-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0003_ace_amount_ace_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('details_of_expenditure', models.CharField(blank=True, max_length=120, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=120, null=True)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ace_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ace.ace')),
            ],
        ),
    ]
