# Generated by Django 5.0.1 on 2024-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0003_alter_ace_section_head_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ace',
            name='quantity',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='designation',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='general_manager',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='gm_rejection_reason',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
