# Generated by Django 4.1.3 on 2024-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0004_ace_quantity_alter_ace_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='asset_number',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
