# Generated by Django 4.1.3 on 2023-12-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0004_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='to_be_withdrawn',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='withdrawn',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
