# Generated by Django 4.1.3 on 2024-01-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0005_budget_to_be_withdrawn_transactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='budget',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Ace.budget'),
            preserve_default=False,
        ),
    ]
