# Generated by Django 4.1.3 on 2024-02-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0005_alter_ace_asset_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='accounting_officer_rejection_reason',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='asset_number',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='section_head_rejection_reason',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
