# Generated by Django 4.1.3 on 2024-02-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0006_alter_ace_accounting_officer_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='accounting_officer_rejection_reason',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='asset_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='designation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='section_head_rejection_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
