# Generated by Django 4.1.3 on 2024-01-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0006_transactions_ace_transactions_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='ace',
            new_name='ace2',
        ),
    ]
