# Generated by Django 4.1.3 on 2024-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0007_rename_ace_transactions_ace2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='approval_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
