# Generated by Django 4.1.3 on 2024-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0008_alter_ace_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ace',
            name='approval_code',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
