# Generated by Django 4.1.3 on 2024-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0009_ace_approval_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ace',
            name='fm_rejected',
        ),
        migrations.RemoveField(
            model_name='ace',
            name='gm_rejected',
        ),
        migrations.AddField(
            model_name='ace',
            name='accounting_officer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='accounting_officer_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='accounting_officer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='accounting_officer_rejection_reason',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='approver1_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='approver2_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='approver3_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='finance_manager',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='general_manager',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='section_head',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='section_head_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='section_head_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ace',
            name='section_head_rejection_reason',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
