# Generated by Django 4.1.3 on 2024-01-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0010_remove_ace_fm_rejected_remove_ace_gm_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ace',
            name='fm_approved',
        ),
    ]
