# Generated by Django 4.1.3 on 2024-01-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0011_remove_ace_fm_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ace',
            name='approver1_date',
        ),
        migrations.RemoveField(
            model_name='ace',
            name='approver2_date',
        ),
        migrations.RemoveField(
            model_name='ace',
            name='approver3_date',
        ),
        migrations.AlterField(
            model_name='ace',
            name='finance_manager',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='general_manager',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
