# Generated by Django 4.1.3 on 2024-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0012_remove_ace_approver1_date_remove_ace_approver2_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ace',
            name='accounting_officer_approval_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='accounting_officer_rejection_reason',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='approved_by',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='finance_manager',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='fm_approval_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='ace',
            name='section_head_approval_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
