# Generated by Django 4.1.3 on 2024-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ace', '0013_alter_ace_accounting_officer_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='awaiting_sanctioning',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
