version: "3.9"
services:
  tika:
    image: apache/tika:2.9.2.0
    container_name: tika-server
    restart:
      always
    ports:
      - "9998:9998" # Expose port 9998 for the Tika server
    networks:
      - elastic_network
    environment:
      - TIKA_CONFIG_PATH=/tika-config.xml # Optional: Path to custom Tika configuration
    volumes:
      - ./tika-config.xml:/tika-config.xml # Optional: Mount custom Tika config if needed

  elasticsearch:
    image: elasticsearch:7.14.0
    restart:
      always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    networks:
      - elastic_network
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  kibana:
    image: kibana:8.2.2
    ports:
      - target: 5601
        published: 5601
    networks:
      - elastic_network

  fscrawler:
    image: dadoonet/fscrawler:2.10-SNAPSHOT
    container_name: fscrawler
    restart: always
    volumes:
      - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
      - ${PWD}/config:/root/.fscrawler
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - ${PWD}/external:/usr/share/fscrawler/external
    ports:
      - 8580:8080
    networks:
      - elastic_network
    command: fscrawler idx --restart --rest

volumes:
  es_data:
    driver: local

networks:
  elastic_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16
          gateway: 172.40.0.1
