# Generated by Django 4.1.3 on 2024-02-16 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('root_cause', models.TextField(blank=True, max_length=400, null=True)),
                ('violation_standard_reference', models.CharField(blank=True, max_length=400, null=True, verbose_name='Violation Standard Reference')),
                ('recommended_corrective_action', models.CharField(max_length=300, verbose_name='Recommended Corrective Action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='static/nonconformity_files/', verbose_name='Attachment')),
                ('plan_of_action', models.TextField(blank=True, max_length=400, null=True, verbose_name='Plan of Action')),
                ('expected_completion_date', models.DateField(blank=True, null=True, verbose_name='Expected Completion Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='created', max_length=20)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity.nonconformity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
