# Generated by Django 5.0 on 2024-01-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonconformity',
            old_name='assigned_to',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='nonconformity',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/noneconformity_files/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='recommended_corrective_action',
            field=models.CharField(default=1, max_length=300, verbose_name='Recommended Corrective Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='violation_standard_reference',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Violation Standard Reference'),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
    ]
