# Generated by Django 5.0 on 2024-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0002_rename_assigned_to_nonconformity_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='violation_standard_reference',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Violation Standard Reference'),
        ),
    ]
