# Generated by Django 4.1.3 on 2024-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0003_alter_nonconformity_violation_standard_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='response',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='created', max_length=20),
        ),
        migrations.DeleteModel(
            name='NonconformityResponse',
        ),
    ]
