# Generated by Django 4.1.3 on 2024-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0004_nonconformity_response_nonconformity_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonconformity',
            old_name='is_accepted',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='nonconformity',
            name='is_resolved',
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='response',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='created', max_length=20),
        ),
    ]
