# Generated by Django 4.1.3 on 2024-01-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0005_rename_is_accepted_nonconformity_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='is_read',
        ),
    ]
