# Generated by Django 4.1.3 on 2024-01-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nonconformity', '0006_remove_nonconformity_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='response',
        ),
        migrations.RemoveField(
            model_name='nonconformity',
            name='status',
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='static/nonconformity_files/', verbose_name='Attachment'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='created', max_length=20)),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformity.nonconformity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='responses',
            field=models.ManyToManyField(related_name='nonconformity_responses', through='nonconformity.Response', to=settings.AUTH_USER_MODEL),
        ),
    ]
