# Generated by Django 4.1.3 on 2024-01-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0007_remove_nonconformity_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformity',
            name='responses',
        ),
        migrations.AlterField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
