# Generated by Django 4.1.3 on 2024-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0008_remove_nonconformity_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='root_cause',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
