# Generated by Django 4.2.7 on 2024-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0009_nonconformity_root_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Completion Date'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='plan_of_action',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Plan of Action'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='created', max_length=20),
        ),
    ]
