# Generated by Django 4.1.3 on 2023-03-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='depot',
            new_name='Depot',
        ),
    ]
