# Generated by Django 4.1.3 on 2023-03-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_depot_userprofile_depot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Depot',
            new_name='depot',
        ),
    ]
