# Generated by Django 4.1.3 on 2024-02-27 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(default=datetime.date(2024, 2, 27)),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='EC Number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('status', models.CharField(blank=True, max_length=30)),
                ('last_reset', models.DateField(default=datetime.date(2024, 2, 27))),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.depots')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.designations')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.districts')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.regions')),
                ('roles', models.ManyToManyField(blank=True, max_length=100, to='users.roles')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sections')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
