# Generated by Django 4.1.3 on 2023-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
