# Generated by Django 4.1.3 on 2023-10-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_roles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
