# Generated by Django 4.1.3 on 2023-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='designations',
            name='identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='designations',
            name='chk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='designations',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
