# Generated by Django 4.1.3 on 2023-10-16 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_designations_identifier_alter_designations_chk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(default=datetime.date(2023, 10, 16)),
        ),
    ]
