# Generated by Django 4.1.3 on 2024-01-04 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(default=datetime.date(2024, 1, 4)),
        ),
    ]
