<<<<<<< HEAD
# Generated by Django 4.1.3 on 2024-01-09 18:13
=======
# Generated by Django 4.1.3 on 2024-01-04 11:34
>>>>>>> 380af8bf528b21d25cd2a07b26a9115999952133

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2024, 1, 9)),
=======
            field=models.DateField(default=datetime.date(2024, 1, 4)),
>>>>>>> 380af8bf528b21d25cd2a07b26a9115999952133
        ),
    ]
