<<<<<<< HEAD
# Generated by Django 4.1.3 on 2024-01-10 14:08
=======
# Generated by Django 5.0.1 on 2024-01-09 10:53
>>>>>>> 380af8bf528b21d25cd2a07b26a9115999952133

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2024, 1, 10)),
=======
            field=models.DateField(default=datetime.date(2024, 1, 9)),
>>>>>>> 380af8bf528b21d25cd2a07b26a9115999952133
        ),
    ]
