# Generated by Django 4.1.3 on 2024-01-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_last_reset'),
        ('users', '0019_alter_userprofile_last_reset'),
    ]

    operations = [
    ]
