# Generated by Django 4.1.3 on 2024-01-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userprofile_last_reset'),
        ('users', '0023_alter_userprofile_last_reset'),
    ]

    operations = [
    ]
