# Generated by Django 4.1.3 on 2024-01-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_last_reset_notification'),
        ('users', '0025_alter_userprofile_last_reset'),
    ]

    operations = [
    ]
