# Generated by Django 4.1.3 on 2024-01-25 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_merge_20240122_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(default=datetime.date(2024, 1, 25)),
        ),
    ]
