# Generated by Django 4.1.3 on 2024-01-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_merge_20240122_1420'),
        ('users', '0027_alter_userprofile_last_reset'),
    ]

    operations = [
    ]
