# Generated by Django 5.0.1 on 2024-01-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20240124_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
