# Generated by Django 4.2.7 on 2024-02-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20240122_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.districts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sections'),
        ),
    ]
