# Generated by Django 5.0.1 on 2024-02-02 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateField(default=datetime.date(2024, 2, 2)),
        ),
    ]
