# Generated by Django 4.2.7 on 2024-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_userprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
