# Generated by Django 4.2.7 on 2024-02-07 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userprofile_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.designations'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
