# Generated by Django 4.2.7 on 2024-02-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.depots'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.regions'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(to='users.roles'),
        ),
    ]
