# Generated by Django 4.2.7 on 2024-02-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_userprofile_depot_alter_userprofile_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='users.roles'),
        ),
    ]
