import csv
import random
from datetime import datetime, timedelta

def get_random_date(start_date, end_date):
    """
    Returns a random date between start_date and end_date (inclusive).
    """
    days_between = (end_date - start_date).days
    random_days = random.randint(0, days_between)
    random_date = start_date + timedelta(days=random_days)
    return random_date.strftime("%Y-%m-%d")

locations = [
    "Alex Park - Part",
    "Alex Park - Part",
    "Amalinda",
    "Amalinda Farm",
    "Ambleside",
    "Amby",
    "Arbour Cres",
    "Art Farm",
    "Ashbritle",
    "Ashdown Park",
    "Athlone",
    "Athlone - Part",
    "Avenues",
    "Avondale",
    "Avondale West",
    "Avonlea - Part",
    "Avonlea West",
    "Ballantyne Park",
    "Bannockburn",
    "Barrington Rd Area",
    "Belgravia",
    "Belvedere",
    "Borrowdale",
    "Borrowdale Brook",
    "Borrowdale N",
    "Bothashof",
    "Budiriro",
    "Carrick",
    "Chadcombe",
    "Chedgelow",
    "Chikurubi",
    "Chiltern Hill",
    "Chishawasha",
    "Chishawasha",
    "Chisipite",
    "Colne Valley",
    "Colne Valley",
    "Colray",
    "Colray",
    "Coronation Park",
    "Glen Norah",
    "Glen Norah A - Part",
    "Glen Wood",
    "Glenview",
    "Glenview - Part",
    "Greendale - Part",
    "Greendale - Part",
    "Greendale - Part",
    "Greendcroft",
    "Greengrove",
    "Greystone Park",
    "Grobbie Park",
    "Groombridge",
    "Guildform Estate",
    "Gunhill",
    "Haig Park",
    "Harare Rd W",
    "Harava Dam",
    "Hatcliffe",
    "Hatfield West",
    "Hat-Twentydales -Part",
    "Hatlands Farm",
    "Helensvale",
    "Helensvale S",
    "Highfield",
    "Highlands - Part",
    "Highlands - Part",
    "Highlands - Part",
    "Hillside",
    "Hopley",
    "Hunyani Poort",
    "Induna",
    "Ingwe Farm",
    "Jerusalem",
    "Kambuzuma",
    "Kambuzuma",
    "Kambuzuma South",
    "Kensington",
    "Kensington",
    "Kingsmead",
    "Mabvuku",
    "Machipisa",
    "Malvern",
    "Mandalay Park",
    "Mandara",
    "Marimba Park",
    "Marlborough",
    "Mayfield Park",
    "Mbare",
    "Merwede",
    "Meyrick Park",
    "Midlands",
    "Milton Park",
    "Monavale",
    "Msasa Park",
    "Mt Pleasant & Heights",
    "Mt Hampden",
    "Matidoda",
    "Mufakose",
    "Mutare Rd",
    "Newlands",
    "Newlands East",
    "Northwood",
    "Old Highfields",
    "Pangula",
    "Paradise Park",
    "Park Meadowlands",
    "Parkridge",
    "Parkridge Estate",
    "Parktown",
    "Pension Farm",
    "Pension Farm",
    "Pomona",
    "Prospect East",
    "Prospect West",
    "Queensdale",
    "Quinnington",
    "Quinnington S",
    "Rambabvu",
    "Reiforntein",
    "Sherwood Park - Part",
    "Somerby Area",
    "Spring Heights",
    "Stanbury Park",
    "Startmore Farm",
    "Stoneridge Rd",
    "Strathaven",
    "Sunridge",
    "Tafara",
    "The Grange",
    "Thornpark",
    "Twentydales Ext.",
    "Tynwald North",
    "Tynwald South",
    "Umwinsidale",
    "Uplands",
    "Upper Mt Hampden",
    "Upper Reaches Rd",
    "Vainona",
    "Valencedene",
    "Waldon Area",
    "Warren Park",
    "Warren Park - Part",
    "Warren Park - Part",
    "Warren Park E",
    "Waterfalls",
    "Westlea",
    "Westwood",
    "Widdecombe",
    "Wilmington Park",
    "Winchdon",
    "Southlea Park",
    "Rydale Ridge",
    "Whitecliffe",
    "Southerton Residential",
    "Cotswold Hills",
    "Cranborne Park",
    "Creagh",
    "Crowborough",
    "Crowborough Estate",
    "Crowhill",
    "Draycot",
    "Dzivaresekwa",
    "Eastlea",
    "Eastlea",
    "Emerald Hill",
    "Epworth",
    "Getwyn",
    "Glen Lorne",
    "Glen Lorne West",
    "Zengeza 1, 2,3, 4 & 5",
    "Zengeza 5 Ext",
    "Guzha",
    "Unit J",
    "St Mary’s",
    "Manyame Park",
    "Kintyre",
    "Komani",
    "Kutsaga",
    "Kuwadzana",
    "Lake Chivero",
    "Langford Farm",
    "Lewisam",
    "Lincoln Green",
    "Little Norfolk",
    "Logan Park",
    "Lonchinvar",
    "Luna",
    "Lusaka",
    "Mabelreign",
    "Mabelreign N",
    "Reiforntein - Part",
    "Rhodesville",
    "Ridgeview",
    "Rolf Valley South",
    "Rolf Valley N",
    "Ruwa",
    "Ruwa",
    "S Mazorodze Areas",
    "Safron Area",
    "San Souci Rd Area",
    "San Souci Rd Area",
    "Seki Rd Area",
    "Seki Rd N",
    "Sentosa",
    "Sherwood Park - Part",
    "Seke Unit A, B, C, D, E",
    "Seke Unit F, G Old",
    "Seke Unit K, L, M",
    "Town Centre",
    "Seke Unit B, Makoni",
    "Seke Unit M,N, O, P",
    "Police Flats, Unit B",
    "Murisa T/Ship, Dema",
    "Manyame Park",
    "St Mary’s",
    "Mayambara",
    "GDC",
    "Jaggers, Chibuku, DMB",
    "Southern Granite",
    "Sewage Works",
    "Surface Investments",
    "Parts of Unit K",
    "22 Miles",
    "3 Brigade",
    "3-2 Battalion",
    "4 Brigade",
    "Adams Barracks",
    "Africa University",
    "All of Masvingo Province",
    "Anderson school",
    "Arda Transau",
    "Avila",
    "Bangala",
    "Bangazani Dam",
    "Bannockburn",
    "Bende",
    "Bikita",
    "Bikita Minerals",
    "Bikita Village",
    "Birchenough Bridge",
    "Birthday Mine",
    "BNR",
    "Bonda",
    "Bonda Irrigation",
    "Bordervale",
    "Buffalo Range",
    "Buhera",
    "Bumba",
    "Burma Valley"
]

depots = [
    "Mabelreign Depot",
    "Borrowdale Depot",
    "Glen View Depot",
    "Kuwadzana Depot",
    "Mabvuku Depot",
    "Ruwa Depot",
    "Southerton Depot",
    "Warren Park Depot",
    "Waterfalls Depot",
    "CBD Depot",
    "Makoni Depot",
    "Zengeza Depot",
    "Seke"
]

districts = [
    "Chitungwiza District",
    "North District",
    "South District",
    "East District"
]

regions = [
    "Harare",
    "East",
    "South",
    "West"
]

data = []

for _ in range(100):
    location = random.choice(locations)
    depot = random.choice(depots)
    district = random.choice(districts)
    region = random.choice(regions)
    
    start_date = datetime(2023, 12, 1)
    end_date = datetime(2024, 1, 9)
    random_date = get_random_date(start_date, end_date)
    created_at = random_date
    
    data.append([location, depot, district, region, created_at])

# Save the data as a CSV file
filename = "maintenance_data.csv"
with open(filename, "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["location", "depot", "district", "region", "created_at"])  # Write header
    writer.writerows(data)

print(f"Data has been saved as {filename}")