"""
Django settings for beii_v1 project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import sys, os
from datetime import timedelta
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7per#nouy422m0!hn0!ecb7ltnq#!^#g!2r5&%^5c%v(!ivv&a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '172.16.8.97', '172.16.8.22', '127.0.0.1','172.16.8.98']

CORS_ALLOWED_ORIGINS = [
    "http://172.16.8.97",
    "http://172.16.8.98",
    "http://172.16.8.97:3200",
    "http://localhost:3000",
    "http://172.16.8.98:9300"
]

CSRF_TRUSTED_ORIGINS = ['http://172.16.8.97', "http://172.16.8.97:3200","http://172.16.8.98"]

CORS_ALLOW_HEADERS = ('content-disposition', 'accept-encoding',
                      'content-type', 'accept', 'origin', 'authorization')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "users.serializers.MyTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


# Application definition
sys.path.insert(0, os.path.join(BASE_DIR, 'it'))
sys.path.insert(1, os.path.join(BASE_DIR, 'engineering'))
sys.path.insert(2, os.path.join(BASE_DIR, 'commercials'))
sys.path.insert(3, os.path.join(BASE_DIR, 'hr'))
sys.path.insert(4, os.path.join(BASE_DIR, 'reports'))
sys.path.insert(5, os.path.join(BASE_DIR, 'api/ops_maintenance'))
sys.path.insert(6, os.path.join(BASE_DIR, 'finance'))
sys.path.insert(7, os.path.join(BASE_DIR, 'miscellaneous'))
sys.path.insert(8, os.path.join(BASE_DIR, 'executive'))

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework_simplejwt',
    'risk.audit.checklist',
    'risk.audit.nonconformity',
    'it.beii_auth.apps.BeiiAuthConfig',
    'it.users.apps.UsersConfig',
    'executive.exec_dashboards.apps.ExecDashboardsConfig',
    'knowledge_center',
    'Docs',
    'processes.apps.ProcessesConfig',
    'process_risks.apps.ProcessRisksConfig',
    'finance.Ace.apps.AceConfig',
    'sweetify',
    'mathfilters',
    
    'commecial.tempertockens',
    'competence_building.apps.CompetenceBuildingConfig'

    # 'finance.tenders.apps.TendersConfig',
    # 'engineering.reticulations.apps.ReticulationsConfig',
    # 'commercials.connections.apps.ConnectionsConfig',
    # 'Pettycash.apps.PettycashConfig',
    # 'hr.okr.apps.OkrConfig',
    # 'reports.beii_reports.apps.BeiiReportsConfig',
    # 'api.ops_maintenance.safety_operations.apps.SafetyOperationsConfig',

    # 'miscellaneous.knowledge_center.apps.KnowledgeCenterConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': '127.0.0.1:9200/',  # Replace with your Elasticsearch host and port
    },
}

ROOT_URLCONF = 'beii_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beii_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'beii',
    #     'USER': 'beii_user',
    #     'PASSWORD': 'v4mnwVrOsAupSY0k',
    #     'HOST': '172.16.8.22'
    # }
    # Localhost
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'beii',
    #     'USER': 'Excellence',
    #     'PASSWORD': 'Z3tdc_it@2021_',
    #     'HOST': 'localhost'
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'beii',
    #     'USER': 'root',
    #     'PASSWORD': '',
    #     'HOST': 'localhost',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'beii',
        'USER': 'excellence',
        'PASSWORD': 'Z3tdc_it@2021_',
        'HOST': 'localhost'
    }
    # Localhost
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'beii',
    #     'USER': 'Excellence',
    #     'PASSWORD': 'Z3tdc_it@2021_',
    #     'HOST': 'localhost'
    # }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Harare'

USE_I18N = True

USE_TZ = True
LOGIN_REDIRECT_URL='/'
LOGIN_URL = '/accounts/login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static",BASE_DIR / "uploads",]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/dashboards/overview'
