# Generated by Django 4.1.3 on 2024-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process_maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=400)),
                ('section', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
