# Generated by Django 4.1.3 on 2024-01-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsuploads',
            old_name='filepath',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='formsuploads',
            old_name='file_type',
            new_name='filetype',
        ),
    ]
