# Generated by Django 4.1.3 on 2024-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_maps',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='process_maps',
            name='sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
