# Generated by Django 4.1.3 on 2024-01-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_rename_filepath_formsuploads_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WorkInstr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file', models.FileField(null=True, upload_to='')),
                ('filepath', models.CharField(max_length=400)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.departments')),
            ],
        ),
        migrations.DeleteModel(
            name='FormsUploads',
        ),
    ]
