# Generated by Django 5.0.1 on 2024-01-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_rename_filepath_formsuploads_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
