# Generated by Django 4.1.3 on 2024-02-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_departments_workinstr_delete_formsuploads'),
        ('processes', '0003_filetype'),
    ]

    operations = [
    ]
