# Generated by Django 4.1.3 on 2024-02-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_merge_20240207_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filetype',
        ),
    ]
