# Generated by Django 4.1.3 on 2024-02-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file', models.FileField(null=True, upload_to='')),
                ('filepath', models.CharField(max_length=400)),
                ('section', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_risks.departments')),
            ],
        ),
    ]
