# Generated by Django 4.1.3 on 2024-01-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_risks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfiles',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='RiskFiles',
        ),
    ]
