# Generated by Django 4.1.3 on 2024-02-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_risks', '0002_riskfiles_created_at_riskfiles_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfiles',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
