# Generated by Django 4.1.3 on 2024-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_risks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfiles',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
