# Generated by Django 4.1.3 on 2024-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_risks', '0004_riskfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
