# Generated by Django 4.1.3 on 2024-01-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_risks', '0005_alter_departments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfiles',
            name='filepath',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
