# Generated by Django 4.1.3 on 2024-01-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
