# Generated by Django 4.1.3 on 2024-02-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
