# Generated by Django 5.0.1 on 2024-03-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ace', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('rfq_type', models.CharField(blank=True, max_length=15, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_code_of_expenditure', models.CharField(blank=True, max_length=100, null=True)),
                ('scope_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('proc_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('quotation1', models.FileField(upload_to='uploads/finance/rfq')),
                ('quotation2', models.FileField(upload_to='uploads/finance/rfq')),
                ('quotation3', models.FileField(upload_to='uploads/finance/rfq')),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=120, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('section_head', models.CharField(blank=True, max_length=100, null=True)),
                ('finance_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('general_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('general_manager_approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('general_manager_approval_date', models.DateField(blank=True, null=True)),
                ('general_manager_rejection_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('finance_manager_approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('finance_manager_approval_date', models.DateField(blank=True, null=True)),
                ('finance_manager_rejection_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('section_head_approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('section_head_approval_date', models.DateField(blank=True, null=True)),
                ('section_head_rejection_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('ace', models.ForeignKey(blank=True, db_column='ace_id2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ace.ace')),
            ],
            options={
                'db_table': 'rfq',
            },
        ),
    ]
