# Generated by Django 4.1.3 on 2024-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspections',
            old_name='location',
            new_name='depot',
        ),
        migrations.AddField(
            model_name='inspections',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspections',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
