# Generated by Django 4.1.3 on 2024-01-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0002_rename_location_inspections_depot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='location',
            new_name='depot',
        ),
    ]
