# Generated by Django 4.1.3 on 2024-01-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0004_inspections_location_maintenance_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbnc',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='ics_ref',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='ndm_ref',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pbnc',
            name='reciept_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
