# Generated by Django 4.2.7 on 2024-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0005_pbnc_address_pbnc_capacity_pbnc_ics_ref_pbnc_ndm_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
