# Generated by Django 4.1.3 on 2024-02-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAULTS_REPORTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot', models.CharField(blank=True, max_length=100, null=True)),
                ('incoming_faults', models.CharField(blank=True, max_length=50, null=True)),
                ('pending_jobs', models.CharField(blank=True, max_length=50, null=True)),
                ('active_jobs', models.CharField(blank=True, max_length=50, null=True)),
                ('total_outstanding', models.CharField(blank=True, max_length=50, null=True)),
                ('closed', models.CharField(blank=True, max_length=50, null=True)),
                ('total_faults', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage_of_outstanding', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NETWORK_AVAILABILITY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLANS_AND_REPORTS_FIELDS_VIEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('report_period', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.CharField(blank=True, max_length=100, null=True)),
                ('date_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
