# Generated by Django 4.1.3 on 2024-02-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exec_dashboards', '0007_faults_reports_network_availability_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAULTS_REPORTS',
        ),
        migrations.DeleteModel(
            name='NETWORK_AVAILABILITY',
        ),
        migrations.DeleteModel(
            name='PLANS_AND_REPORTS_FIELDS_VIEW',
        ),
    ]
