# Generated by Django 4.1.3 on 2024-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('token_number', models.CharField(max_length=50)),
                ('date_purchased', models.DateField()),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
    ]
