# Generated by Django 4.1.3 on 2024-01-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('cat_1', models.CharField(max_length=100)),
                ('cat_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='First_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_center.filetype')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('sub_category_1', models.CharField(max_length=100)),
                ('sub_category_2', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=400)),
                ('section', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='knowledge_center.first_category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='knowledge_center.filetype')),
            ],
        ),
    ]
