# Generated by Django 4.1.3 on 2024-01-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_center', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_model',
        ),
    ]
