# Generated by Django 4.1.3 on 2024-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_center', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_model',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='cat_1',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='cat_2',
        ),
        migrations.RemoveField(
            model_name='first_category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='region',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='section',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='sub_category_1',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='sub_category_2',
        ),
        migrations.RemoveField(
            model_name='knowledgecenter',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='secondary_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='secondary_category',
            name='name',
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
