# Generated by Django 4.1.3 on 2024-01-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_center', '0002_delete_my_model_remove_categories_cat_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_1',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='cat_2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first_category',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='created_at',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='created_by',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='file_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='filepath',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='region',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='section',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='sub_category_1',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='sub_category_2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgecenter',
            name='updated_at',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondary_category',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='knowledge_center.first_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondary_category',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
