from .appraisal import AppraisalCreateView, AppraisalTemplateView, AppraisalUpdateView
from .experience import ExperienceCreateView, experience_list_api, ExperienceListView, AppraisalExperienceCreateView, AppraisalExperienceUpdateView
from .performance_review import PerformancePlanAndAssessmentAppraisalTemplateView, PerformanceReviewsApprovalView, PerformancePlanAndAssessmentTemplateView
from .training import TrainingAndDevelopmentUpdateView
from .kra.kra import KRATemplateView, KRACreateView, KRAUpdateView
from .kra.activity import KraActivityIndexTemplateView, KraActivityCreateView, KraActivityUpdateView
from .kra.targets import TargetsIndexView, TargetCreateView, TargetUpdateView, TargetScoreUpdateView
from .qualification import UserQualificationTemplateView