INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (1, 'Legislation', 'Electricity Acts', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (2, 'Legislation', 'General Legislation', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (4, 'Legislation', 'Statutory Instruments', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (6, 'POLICIES & GUIDELINES', 'Commercial', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (7, 'POLICIES & GUIDELINES', 'Human Resources', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (8, 'POLICIES & GUIDELINES', 'Engineering', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (9, 'POLICIES & GUIDELINES', 'Finance', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (11, 'POLICIES & GUIDELINES', 'ICT', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (12, 'POLICIES & GUIDELINES', 'Commercial', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (13, 'POLICIES & GUIDELINES', 'Risk', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (14, 'POLICIES & GUIDELINES', 'Human Resources', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (15, 'POLICIES & GUIDELINES', 'Engineering', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (16, 'POLICIES & GUIDELINES', 'Finance', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (17, 'POLICIES & GUIDELINES', 'ICT', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (18, 'POLICIES & GUIDELINES', 'Risk', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (20, 'PUBLICATIONS', '', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (22, 'ENGINEERING', '1_10', 'Reports');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (23, 'ENGINEERING', '1_10', 'Protection');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (24, 'ENGINEERING', '1_10', 'Earthing');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (25, 'ENGINEERING', '1_10', 'Transformers');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (26, 'ENGINEERING', '1_10', 'Fuses');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (27, 'ENGINEERING', '1_10', 'Instruments, Meters and Metering');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (28, 'ENGINEERING', '1_10', 'Transformer Gaskets');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (29, 'ENGINEERING', '1_10', 'Switchgear');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (30, 'ENGINEERING', '1_10', 'Post Office Regulations');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (31, 'ENGINEERING', '1_10', 'Insulating Oils');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (33, 'ENGINEERING', '11_20', 'Clearance Distances');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (34, 'ENGINEERING', '11_20', 'Mine Department Regulations');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (35, 'ENGINEERING', '11_20', 'Interruption of Supply Notice to Consumers');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (36, 'ENGINEERING', '11_20', 'Water Samples and Painting to Consumers');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (37, 'ENGINEERING', '11_20', 'Cables');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (38, 'ENGINEERING', '11_20', 'Capital Works and Expenditure ');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (39, 'ENGINEERING', '11_20', 'Government planning and Wayleaves');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (40, 'ENGINEERING', '11_20', 'Phase Rotation and Colouring');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (41, 'ENGINEERING', '11_20', 'Insulators and Bushings');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (42, 'ENGINEERING', '11_20', 'Locks and Keys');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (44, 'ENGINEERING', '21_30', 'RMasts, Poles, Stays and Crossarms');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (45, 'ENGINEERING', '21_30', 'Substations');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (46, 'ENGINEERING', '21_30', 'Fire Fighting');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (47, 'ENGINEERING', '21_30', 'Defective and Damaged Equipment Insurance & Guarantees');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (48, 'ENGINEERING', '21_30', 'Services and Service Equipment');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (49, 'ENGINEERING', '21_30', 'Consumer\'s Equipment and installation');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (50, 'ENGINEERING', '21_30', 'Lifting Equipment');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (51, 'ENGINEERING', '21_30', 'Transport');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (52, 'ENGINEERING', '21_30', 'Lighting Protection and Arrestors');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (53, 'ENGINEERING', '21_30', 'Insulation');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (55, 'ENGINEERING', '31_45', 'Cable Jointing Laying');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (56, 'ENGINEERING', '31_45', 'Capacitors and Power Factor Correction');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (57, 'ENGINEERING', '31_45', 'Explosive and Magazine');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (58, 'ENGINEERING', '31_45', 'Standard Stock Items');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (59, 'ENGINEERING', '31_45', 'Cradles and Guards');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (60, 'ENGINEERING', '31_45', 'Standard 11Kv Line Construction');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (61, 'ENGINEERING', '31_45', 'Conductors, Earthwires and Accessories');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (62, 'ENGINEERING', '31_45', 'Road, Rail, and Line Crossings');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (63, 'ENGINEERING', '31_45', 'Z.E.T.D.C Regulations and Safety Precautions');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (64, 'ENGINEERING', '31_45', 'Power Stations');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (65, 'ENGINEERING', '31_45', 'Substation Batteries');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (66, 'ENGINEERING', '31_45', 'Safety Rules for Operation and Maintenance Switching Authorization');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (67, 'ENGINEERING', '31_45', 'High Mast Lighting');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (68, 'ENGINEERING', '31_45', 'Planning Policy on Firm Capacity');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (69, 'ENGINEERING', '31_45', 'Procurement');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (71, 'USER MANUALS', 'Commercial', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (72, 'USER MANUALS', 'Human Resources', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (73, 'USER MANUALS', 'Engineering', 'Switchgear');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (74, 'USER MANUALS', 'Engineering', 'Drone Technology');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (75, 'USER MANUALS', 'Engineering', 'NDM');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (76, 'USER MANUALS', 'Engineering', 'GIS');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (77, 'USER MANUALS', 'Engineering', 'iTrack Zimbabwe Geotrack Connect Manual');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (78, 'USER MANUALS', 'Engineering', 'SAP');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (79, 'USER MANUALS', 'Engineering', 'OMS');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (80, 'USER MANUALS', 'Finance', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (81, 'USER MANUALS', 'ICT', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (82, 'USER MANUALS', 'Risk', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (84, 'STANDARDS, SPECIFICATIONS & DRWAINGS', 'Drawings', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (85, 'STANDARDS, SPECIFICATIONS & DRWAINGS', 'Standards', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (86, 'STANDARDS, SPECIFICATIONS & DRWAINGS', 'Specifications', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (88, 'KNOWLEDGE BASE', 'Commercial', 'Client Interaction Risks');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (89, 'KNOWLEDGE BASE', 'Commercial', 'Payment Risks');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (90, 'KNOWLEDGE BASE', 'Commercial', 'Revenue Assurance Risks');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (91, 'KNOWLEDGE BASE', 'Engineering', 'Maintanance');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (92, 'KNOWLEDGE BASE', 'Engineering', 'Drone Technology');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (93, 'KNOWLEDGE BASE', 'HR', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (94, 'KNOWLEDGE BASE', 'Risk', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (95, 'KNOWLEDGE BASE', 'Finance', '');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (96, 'KNOWLEDGE BASE', 'ICT', 'User Support');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (97, 'KNOWLEDGE BASE', 'ICT', 'Network Support');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (98, 'KNOWLEDGE BASE', 'ICT', 'ICT Audit');
INSERT INTO beii_new.knowledge_center_categories (id, file_type, cat_1, cat_2) VALUES (99, 'KNOWLEDGE BASE', 'ICT', 'Trending Technologies');
