INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (1, 'Acts of Parliament', 1);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (2, 'Commercial', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (3, 'Human Resources', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (4, 'Engineering', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (5, 'Finance', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (6, '1_10', 4);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (7, 'ICT', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (8, 'Risk', 2);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (9, 'Statutory Instruments', 1);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (10, 'Legal Registers', 1);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (12, '11_20', 4);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (13, '31_45', 4);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (14, 'Commercial', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (15, 'Human Resources', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (16, 'Engineering', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (17, 'ICT', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (18, 'Risk', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (19, 'Drawings', 6);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (20, 'Standards', 6);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (21, 'Specifications', 6);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (22, 'Commercial', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (23, 'Engineering', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (24, 'HR', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (25, 'Risk', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (26, 'Finance', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (27, 'ICT', 7);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (28, '21_30', 4);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (29, 'Finance', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (30, 'Stakeholder Relations', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (31, 'Legal', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (32, 'Procurement', 5);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (33, 'Commercial', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (34, 'Human Resources', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (35, 'Engineering', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (36, 'ICT', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (37, 'Risk', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (38, 'Stakeholder Relations', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (39, 'Legal', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (40, 'Procurement', 9);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (41, 'Risk management Strategy', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (42, 'Communication management Strategy', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (43, 'Quality Management Strategy', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (44, 'Configuration Management Strategy', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (45, 'Risk Register Template', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (46, 'Lessons Learnt from Previous Projects', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (47, 'Quality Register Template', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (48, 'Configuration Item Record Template', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (49, 'Current Projects', 11);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (50, 'Grids', 10);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (51, 'Approved Drawings', 10);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (52, 'Commissioned Drawings', 10);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (53, 'Structural Drawings', 10);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (54, 'Schematics Drawings', 10);
INSERT INTO beii_new.knowledge_center_first_category (id, name, file_type_id) VALUES (55, 'Building Drawings', 10);
