INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (1, 'Client Interaction Risks', 22, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (2, 'Reports', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (3, 'Protection', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (4, 'Earthing', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (5, 'Transformers', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (6, 'Fuses', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (7, 'Instruments, Meters and Metering', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (8, 'Transformer Gaskets', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (9, 'Switchgear', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (10, 'Post Office Regulations', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (11, 'Insulating Oils', 6, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (13, 'Mine Department Regulations', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (14, 'Interruption of Supply Notice to Consumers', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (15, 'Water Samples and Painting to Consumers', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (16, 'Cables', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (17, 'Capital Works and Expenditure', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (18, 'Government planning and Wayleaves', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (19, 'Phase Rotation and Colouring', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (20, 'Insulators and Bushings', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (21, 'Locks and Keys', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (22, 'Clearance Distances', 12, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (23, 'Cable Jointing Laying', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (24, 'Safety Rules for Operation and Maintenance Switching Authorization', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (25, 'Substations', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (26, 'Services and Service Equipment', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (27, 'Consumer\'s Equipment and installation', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (28, 'Lifting Equipment', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (29, 'Transport', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (30, 'Lighting Protection and Arrestors', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (32, 'Insulation', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (33, 'Capacitors and Power Factor Correction', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (34, 'Explosive and Magazine', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (35, 'Standard Stock Items', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (36, 'Cradles and Guards', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (37, 'Standard 11Kv Line Construction', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (38, 'Conductors, Earthwires and Accessories', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (39, 'High Mast Lighting', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (40, 'Road, Rail, and Line Crossings', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (41, 'Z.E.T.D.C Regulations and Safety Precautions', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (42, 'Power Stations', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (43, 'Substation Batteries', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (44, 'Planning Policy on Firm Capacity', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (53, 'Payment Risks', 22, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (54, 'Revenue Assurance Risks', 22, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (55, 'Maintanance', 23, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (56, 'Drone Technology', 23, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (57, 'User Support', 27, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (58, 'Network Support', 27, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (59, 'ICT Audit', 27, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (60, 'Trending Technologies', 27, 7);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (61, 'Rmast, Poles, Stays and Crossarms', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (62, 'Procurement', 13, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (63, 'Fire Fighting', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (64, 'Defective and Damaged Equipment Insurance & Guarantees', 28, 4);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (66, 'Switchgear', 16, 5);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (67, 'GIS', 16, 5);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (68, 'Commercial', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (69, 'Human Resources', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (70, 'ICT', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (71, 'Engineering', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (72, 'Risk', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (73, 'Procurement', 10, 1);
INSERT INTO beii_new.knowledge_center_secondary_category (id, name, category_id, file_id) VALUES (74, 'Finance', 10, 1);
