
REGIONS = [
    {
        "ics_code": "10",
        "code": "20000",
        "name": "HARARE REGION",
        "parent_code": "20000",
        "region": "HARARE"
    },
    {
      "ics_code": "60",
      "code": "50000",
      "name": "EASTERN REGION",
      "parent_code": "50000",
      "region": "EASTERN"
  },
    {
        "ics_code": "30",
        "code": "30000",
        "name": "NORTHERN REGION",
        "parent_code": "30000",
        "region": "NORTHERN"
    },
    {
        "ics_code": "40",
        "code": "40000",
        "name": "SOUTHERN REGION",
        "parent_code": "40000",
        "region": "SOUTHERN"
    },
    {
        "ics_code": "50",
        "code": "60000",
        "name": "WESTERN REGION",
        "parent_code": "60000",
        "region": "WESTERN"
    }
];

DISTRICTS = [
  {
      "ics_code": "30",
      "code": "32000",
      "name": "BINDURA  DISTRICT ",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "region": "NORTHERN"
  },
  {
      "ics_code": "50",
      "code": "64000",
      "name": "BYO EAST DISTRICT ",
      "parent_code": "60000",
      "district_code": "64000",
      "ics_district_code": "BULAWAYO EAST",
      "region": "WESTERN"
  },
  {
      "ics_code": "50",
      "code": "63000",
      "name": "BYO WEST DISTRICT ",
      "parent_code": "60000",
      "district_code": "63000",
      "ics_district_code": "BULAWAYO WEST",
      "region": "WESTERN"
  },
  {
      "ics_code": "30",
      "code": "31000",
      "name": "CHINHOYI DISTRICT ",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "region": "NORTHERN"
  },
  {
      "ics_code": "10",
      "code": "24000",
      "name": "CHITUNGWIZA DISTRICT",
      "parent_code": "20000",
      "district_code": "24000",
      "ics_district_code": "CHITUNGWIZA",
      "region": "HARARE"
  },
  {
      "ics_code": "50",
      "code": "61000",
      "name": "GWANDA DISTRICT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "region": "WESTERN"
  },
  {
      "ics_code": "40",
      "code": "41000",
      "name": "GWERU DISTRICT ",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "10",
      "code": "21000",
      "name": "HR EAST DISTRICT",
      "parent_code": "20000",
      "district_code": "21000",
      "ics_district_code": "EAST",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "22000",
      "name": "HR NORTH DISTRICT",
      "parent_code": "20000",
      "district_code": "22000",
      "ics_district_code": "NORTH",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "23000",
      "name": "HR SOUTH DISTRICT",
      "parent_code": "20000",
      "district_code": "23000",
      "ics_district_code": "SOUTH",
      "region": "HARARE"
  },
  {
      "ics_code": "50",
      "code": "62000",
      "name": "HWANGE DISTRICT",
      "parent_code": "60000",
      "district_code": "62000",
      "ics_district_code": "HWANGE",
      "region": "WESTERN"
  },
  {
      "ics_code": "30",
      "code": "33000",
      "name": "KADOMA DISTRICT ",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "region": "NORTHERN"
  },
  {
      "ics_code": "40",
      "code": "42000",
      "name": "KWEKWE DISTRICT ",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "60",
      "code": "52000",
      "name": "MANICALAND DISTRICT ",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "region": "EASTERN"
  },
  {
      "ics_code": "30",
      "code": "34000",
      "name": "MARONDERA DISTRICT ",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "53000",
      "name": "MASVINGO DISTRICT ",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "region": "EASTERN"
  },
  {
      "ics_code": "60",
      "code": "51000",
      "name": "MUTARE DISTRICT ",
      "parent_code": "50000",
      "district_code": "51000",
      "ics_district_code": "MUTARE",
      "region": "EASTERN"
  },
  {
      "ics_code": "40",
      "code": "43000",
      "name": "ZVISHAVANE DISTRICT ",
      "parent_code": "40000",
      "district_code": "43000",
      "ics_district_code": "ZVISHAVANE",
      "region": "SOUTHERN"
  }
];

DEPOTS = [
  {
      "ics_code": "30",
      "code": "33050",
      "name": "BEATRICE DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "BEATRICE DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "50",
      "code": "61070",
      "name": "BEITBRIDGE DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "BEITBRIDGE DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "30",
      "code": "32050",
      "name": "BINDURA DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "BINDURA URBAN DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "32060",
      "name": "BINDURA RURAL DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "BINDURA RURAL DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "50",
      "code": "61091",
      "name": "BINGA DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "BINGA DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "10",
      "code": "21030",
      "name": "BORROWDALE DEPOT",
      "parent_code": "20000",
      "district_code": "21000",
      "ics_district_code": "EAST",
      "ics_depot_code": "BORROWDALE DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "30",
      "code": "34050",
      "name": "BROMLEY DEPOT",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "ics_depot_code": "BROMLEY DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "50",
      "code": "64020",
      "name": "BULAWAYO ENVIRONS  DEPOT",
      "parent_code": "60000",
      "district_code": "64000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "BULAWAYO ENVIRONS DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "50",
      "code": "64010",
      "name": "BYO EAST URBAN  DEPOT",
      "parent_code": "60000",
      "district_code": "64000",
      "ics_district_code": "BULAWAYO EAST",
      "ics_depot_code": "BULAWAYO EAST DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "10",
      "code": "21040",
      "name": "CBD DEPOT",
      "parent_code": "20000",
      "district_code": "21000",
      "ics_district_code": "EAST",
      "ics_depot_code": "CBD DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "30",
      "code": "32010",
      "name": "CENTENARY DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "CENTINERY DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "33030",
      "name": "CHEGUTU DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "CHEGUTU URBAN DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "30",
      "code": "33040",
      "name": "CHEGUTU RURAL DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "CHEGUTU RURAL DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "52040",
      "name": "CHIMANIMANI  DEPOT",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "ics_depot_code": "CHIMANIMANI DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "30",
      "code": "31040",
      "name": "CHINHOYI DEPOT",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "ics_depot_code": "CHINHOYI URBAN DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "52030",
      "name": "CHIPINGE  DEPOT",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "ics_depot_code": "CHIPINGE DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "60",
      "code": "53060",
      "name": "CHIREDZI  DEPOT",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "ics_depot_code": "CHIREDZI DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "40",
      "code": "41050",
      "name": "CHIVHU DEPOT",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "ics_depot_code": "CHIVHU DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "30",
      "code": "32070",
      "name": "CONCESSION DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "CONCESSION DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "50",
      "code": "63010",
      "name": "ENTUMBANE DEPOT",
      "parent_code": "60000",
      "district_code": "63000",
      "ics_district_code": "BULAWAYO WEST",
      "ics_depot_code": "ENTUMBANE DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "50",
      "code": "61050",
      "name": "ESIGODINI DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "ESIGODINI DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "50",
      "code": "61060",
      "name": "FILABUSI DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "FILABUSI DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "10",
      "code": "23020",
      "name": "GLENVIEW DEPOT",
      "parent_code": "20000",
      "district_code": "23000",
      "ics_district_code": "SOUTH",
      "ics_depot_code": "GLENVIEW DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "40",
      "code": "42030",
      "name": "GOKWE DEPOT",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "ics_depot_code": "GOKWE DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "60",
      "code": "53030",
      "name": "GUTU  DEPOT",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "ics_depot_code": "GUTU DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "50",
      "code": "61020",
      "name": "GWANDA DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "GWANDA DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "40",
      "code": "41020",
      "name": "GWERU ENVIRONS DEPOT",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "ics_depot_code": None,
      "region": "SOUTHERN"
  },
  {
      "ics_code": "40",
      "code": "41010",
      "name": "GWERU URBAN DEPOT",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "ics_depot_code": "GWERU URBAN DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "50",
      "code": "61090",
      "name": "HWANGE DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "HWANGE DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "30",
      "code": "34010",
      "name": "JURU DEPOT",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "ics_depot_code": "JURU DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "33010",
      "name": "KADOMA DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "KADOMA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "33020",
      "name": "KADOMA RURAL DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "KADOMA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "31010",
      "name": "KARIBA DEPOT",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "ics_depot_code": "KARIBA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "31020",
      "name": "KAROI DEPOT",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "ics_depot_code": "KAROI DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "10",
      "code": "22010",
      "name": "KUWADZANA DEPOT",
      "parent_code": "20000",
      "district_code": "22000",
      "ics_district_code": "NORTH",
      "ics_depot_code": "KUWADZANA DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "40",
      "code": "42010",
      "name": "KWEKWE URBAN DEPOT",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "ics_depot_code": "KWEKWE DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "10",
      "code": "22030",
      "name": "MABELREIGN DEPOT",
      "parent_code": "20000",
      "district_code": "22000",
      "ics_district_code": "NORTH",
      "ics_depot_code": "MABELREIGN DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "21020",
      "name": "MABVUKU DEPOT",
      "parent_code": "20000",
      "district_code": "21000",
      "ics_district_code": "EAST",
      "ics_depot_code": "MABVUKU DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "24020",
      "name": "MAKONI DEPOT",
      "parent_code": "20000",
      "district_code": "24000",
      "ics_district_code": "CHITUNGWIZA",
      "ics_depot_code": None,
      "region": "HARARE"
  },
  {
      "ics_code": "30",
      "code": "34030",
      "name": "MARONDERA DEPOT",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "ics_depot_code": "MARONDERA URBAN DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "34040",
      "name": "MARONDERA RURAL DEPOT",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "ics_depot_code": "MARONDERA URBAN DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "53040",
      "name": "MASHAVA  DEPOT",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "ics_depot_code": "MASHAVA DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "60",
      "code": "53020",
      "name": "MASVINGO  DEPOT",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "ics_depot_code": "MASVINGO DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "40",
      "code": "43020",
      "name": "MATAGA DEPOT",
      "parent_code": "40000",
      "district_code": "43000",
      "ics_district_code": "ZVISHAVANE",
      "ics_depot_code": "MATAGA DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "30",
      "code": "31030",
      "name": "MHANGURA DEPOT",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "ics_depot_code": "MHANGURA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "52050",
      "name": "MIDDLE SABI  DEPOT",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "ics_depot_code": "MIDDLE SABI DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "30",
      "code": "32040",
      "name": "MT DARWIN DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "MT DARWIN DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "51020",
      "name": "MUTARE ENVIRONS  DEPOT",
      "parent_code": "50000",
      "district_code": "51000",
      "ics_district_code": "MUTARE",
      "ics_depot_code": "MUTARE ENVIRONS DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "60",
      "code": "51010",
      "name": "MUTARE URBAN  DEPOT",
      "parent_code": "50000",
      "district_code": "51000",
      "ics_district_code": "MUTARE",
      "ics_depot_code": "MUTARE ENVIRONS DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "30",
      "code": "34020",
      "name": "MUTOKO DEPOT",
      "parent_code": "30000",
      "district_code": "34000",
      "ics_district_code": "MARONDERA",
      "ics_depot_code": "MUTOKO/MREWA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "30",
      "code": "31060",
      "name": "MUTORASHANGA DEPOT",
      "parent_code": "30000",
      "district_code": "31000",
      "ics_district_code": "CHINHOYI",
      "ics_depot_code": "MUTORASHANGA DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "40",
      "code": "41030",
      "name": "MVUMA DEPOT",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "ics_depot_code": "MVUMA DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "30",
      "code": "32030",
      "name": "MVURWI DEPOT",
      "parent_code": "30000",
      "district_code": "32000",
      "ics_district_code": "BINDURA",
      "ics_depot_code": "MVURWI DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "40",
      "code": "42050",
      "name": "NEMBUDZIYA DEPOT",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "ics_depot_code": "NEMBUDZIYA DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "40",
      "code": "42020",
      "name": "NKAYI DEPOT",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "ics_depot_code": "NKAYI DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "50",
      "code": "63020",
      "name": "NKETA DEPOT",
      "parent_code": "60000",
      "district_code": "63000",
      "ics_district_code": "BULAWAYO WEST",
      "ics_depot_code": "NKETA DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "30",
      "code": "33060",
      "name": "NORTON DEPOT",
      "parent_code": "30000",
      "district_code": "33000",
      "ics_district_code": "KADOMA",
      "ics_depot_code": "NORTON DEPOT",
      "region": "NORTHERN"
  },
  {
      "ics_code": "60",
      "code": "52010",
      "name": "NYANGA  DEPOT",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "ics_depot_code": "NYANGA DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "50",
      "code": "61030",
      "name": "PLUMTREE DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "PLUMTREE DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "40",
      "code": "42040",
      "name": "REDCLIFF DEPOT",
      "parent_code": "40000",
      "district_code": "42000",
      "ics_district_code": "KWEKWE",
      "ics_depot_code": "REDCLIFF DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "60",
      "code": "52020",
      "name": "RUSAPE  DEPOT",
      "parent_code": "50000",
      "district_code": "52000",
      "ics_district_code": "MANICALAND",
      "ics_depot_code": "RUSAPE DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "60",
      "code": "53050",
      "name": "RUTENGA  DEPOT",
      "parent_code": "50000",
      "district_code": "53000",
      "ics_district_code": "MASVINGO",
      "ics_depot_code": "RUTENGA DEPOT",
      "region": "EASTERN"
  },
  {
      "ics_code": "10",
      "code": "21050",
      "name": "RUWA DEPOT",
      "parent_code": "20000",
      "district_code": "21000",
      "ics_district_code": "EAST",
      "ics_depot_code": "RUWA DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "40",
      "code": "41040",
      "name": "SHURUGWI DEPOT",
      "parent_code": "40000",
      "district_code": "41000",
      "ics_district_code": "GWERU",
      "ics_depot_code": "SHURUGWI DEPOT",
      "region": "SOUTHERN"
  },
  {
      "ics_code": "10",
      "code": "23010",
      "name": "SOUTHERTON DEPOT",
      "parent_code": "20000",
      "district_code": "23000",
      "ics_district_code": "SOUTH",
      "ics_depot_code": "SOUTHERTON DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "50",
      "code": "61040",
      "name": "TURK MINE DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "TURKMINE DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "50",
      "code": "61080",
      "name": "VICTORIA FALLS DEPOT",
      "parent_code": "60000",
      "district_code": "61000",
      "ics_district_code": "GWANDA",
      "ics_depot_code": "VICTORIA FALLS DEPOT",
      "region": "WESTERN"
  },
  {
      "ics_code": "10",
      "code": "22040",
      "name": "WARREN PARK DEPOT",
      "parent_code": "20000",
      "district_code": "22000",
      "ics_district_code": "NORTH",
      "ics_depot_code": "WARREN/WORKINGTON DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "23030",
      "name": "WATERFALLS DEPOT",
      "parent_code": "20000",
      "district_code": "23000",
      "ics_district_code": "SOUTH",
      "ics_depot_code": "WATERFALLS DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "10",
      "code": "24030",
      "name": "ZENGEZA DEPOT",
      "parent_code": "20000",
      "district_code": "24000",
      "ics_district_code": "CHITUNGWIZA",
      "ics_depot_code": "ZENGEZA DEPOT",
      "region": "HARARE"
  },
  {
      "ics_code": "40",
      "code": "43010",
      "name": "ZVISHAVANE DEPOT",
      "parent_code": "40000",
      "district_code": "43000",
      "ics_district_code": "ZVISHAVANE",
      "ics_depot_code": "ZVISHAVANE DEPOT",
      "region": "SOUTHERN"
  }
]

DESIGNATIONS = [
{"id":"2","description":"Accounting - Clerk","chk":"0","identifier":"0"},
{"id":"3","description":"Accounting Officer - Billing","chk":"0","identifier":"1"},
{"id":"4","description":"Accounting Officer - Cash","chk":"0","identifier":"2"},
{"id":"5","description":"Accounting Officer - Cost","chk":"0","identifier":"3"},
{"id":"6","description":"Accounting Officer - Costing","chk":"0","identifier":"0"},
{"id":"7","description":"Accounting Officer - Costs\/Budgets","chk":"0","identifier":"0"},
{"id":"8","description":"Accounting Officer - Creditors","chk":"0","identifier":"0"},
{"id":"9","description":"Accounting Officer - Payments","chk":"0","identifier":"0"},
{"id":"10","description":"Accounting Officer - Revenue","chk":"0","identifier":"4"},
{"id":"11","description":"Accounts Clerk","chk":"0","identifier":"0"},
{"id":"12","description":"Administration Officer","chk":"0","identifier":"6"},
{"id":"13","description":"Apprentice","chk":"0","identifier":"7"},
{"id":"14","description":"Artisan","chk":"0","identifier":"8"},
{"id":"15","description":"Artisan - Auto","chk":"0","identifier":"9"},
{"id":"16","description":"Artisan - Cable Jointer","chk":"0","identifier":"0"},
{"id":"17","description":"Artisan - Civil","chk":"0","identifier":"10"},
{"id":"18","description":"Artisan - Electrical","chk":"0","identifier":"11"},
{"id":"19","description":"Artisan - Inspector","chk":"0","identifier":"0"},
{"id":"20","description":"Artisan - Lines","chk":"0","identifier":"12"},
{"id":"21","description":"Artisan - Mechanic","chk":"0","identifier":"0"},
{"id":"22","description":"Artisan - Motor Mech","chk":"0","identifier":"13"},
{"id":"23","description":"Artisan - Substation","chk":"0","identifier":"0"},
{"id":"24","description":"Artisan Assistant - Auto","chk":"0","identifier":"14"},
{"id":"25","description":"Artisan Assistant - Cable Jointer","chk":"0","identifier":"0"},
{"id":"26","description":"Artisan Assistant - Civil","chk":"0","identifier":"15"},
{"id":"27","description":"Artisan Assistant - Electrical","chk":"0","identifier":"16"},
{"id":"28","description":"Artisan Assistant - Lines","chk":"0","identifier":"17"},
{"id":"29","description":"Artisan Assistant - Mechanic","chk":"0","identifier":"0"},
{"id":"30","description":"Artisan Assistant - Motor Mech","chk":"0","identifier":"18"},
{"id":"31","description":"Artisan Assistant - Power Cables","chk":"0","identifier":"0"},
{"id":"32","description":"Attachee","chk":"0","identifier":"19"},
{"id":"33","description":"Auger - Crane Operator","chk":"0","identifier":"0"},
{"id":"34","description":"Back Office Supervisor","chk":"0","identifier":"0"},
{"id":"35","description":"Banking Hall Supervisor","chk":"0","identifier":"0"},
{"id":"36","description":"Buyer","chk":"0","identifier":"0"},
{"id":"37","description":"Chief Risk Officer","chk":"0","identifier":"21"},
{"id":"38","description":"Clerk","chk":"0","identifier":"22"},
{"id":"39","description":"Clerk - Admin","chk":"0","identifier":"23"},
{"id":"40","description":"Clerk - Cash","chk":"0","identifier":"24"},
{"id":"41","description":"Clerk - Commercial","chk":"0","identifier":"25"},
{"id":"42","description":"Clerk - Costs","chk":"0","identifier":"26"},
{"id":"43","description":"Clerk - Personnel","chk":"0","identifier":"27"},
{"id":"44","description":"Clerk - Records","chk":"0","identifier":"28"},
{"id":"45","description":"Clerk - Revenue Assurance","chk":"0","identifier":"29"},
{"id":"46","description":"Clerk - Sales","chk":"0","identifier":"30"},
{"id":"47","description":"Clerk - Stores","chk":"0","identifier":"31"},
{"id":"48","description":"Clerk - Typist","chk":"0","identifier":"32"},
{"id":"49","description":"Clerk Typist","chk":"0","identifier":"0"},
{"id":"50","description":"Clients Services Officer","chk":"0","identifier":"33"},
{"id":"51","description":"Commercial Clerk","chk":"0","identifier":"0"},
{"id":"52","description":"Commercial Engineer","chk":"0","identifier":"34"},
{"id":"53","description":"Commercial Manager","chk":"0","identifier":"35"},
{"id":"54","description":"Commercial Officer","chk":"0","identifier":"36"},
{"id":"55","description":"Commercial Supervisor","chk":"0","identifier":"37"},
{"id":"56","description":"Commercial  Supervisor","chk":"0","identifier":"0"},
{"id":"57","description":"Commissionaire","chk":"0","identifier":"0"},
{"id":"58","description":"Customer Care Clerk","chk":"0","identifier":"38"},
{"id":"59","description":"Customer Liaison Attendant","chk":"0","identifier":"0"},
{"id":"60","description":"Customer Services Engineer","chk":"0","identifier":"0"},
{"id":"61","description":"Depot Clerk","chk":"0","identifier":"39"},
{"id":"62","description":"District Manager","chk":"0","identifier":"40"},
{"id":"63","description":"Divisional Secretary","chk":"0","identifier":"0"},
{"id":"64","description":"Draughtsperson","chk":"0","identifier":"41"},
{"id":"65","description":"Engineer","chk":"0","identifier":"42"},
{"id":"66","description":"Engineering Manager","chk":"0","identifier":"43"},
{"id":"67","description":"Finance Manager","chk":"0","identifier":"44"},
{"id":"68","description":"Fuel Attendant","chk":"0","identifier":"0"},
{"id":"69","description":"Gang Charge","chk":"0","identifier":"0"},
{"id":"70","description":"Garage Foreperson","chk":"0","identifier":"45"},
{"id":"71","description":"General Manager","chk":"0","identifier":"46"},
{"id":"72","description":"General Worker","chk":"0","identifier":"0"},
{"id":"73","description":"GIS Artisan (Contract)","chk":"0","identifier":"47"},
{"id":"74","description":"GIS Engineer","chk":"0","identifier":"48"},
{"id":"75","description":"GIS Technician","chk":"0","identifier":"49"},
{"id":"76","description":"Guest House Caretaker","chk":"0","identifier":"0"},
{"id":"77","description":"Hardware Technician","chk":"0","identifier":"51"},
{"id":"78","description":"Hardware Technician Assistant","chk":"0","identifier":"0"},
{"id":"79","description":"Health and Safety Officer","chk":"0","identifier":"52"},
{"id":"80","description":"Heavy Duty Driver","chk":"0","identifier":"53"},
{"id":"81","description":"HRAM","chk":"0","identifier":"54"},
{"id":"82","description":"Human Resource Officer","chk":"0","identifier":"55"},
{"id":"83","description":"Industrial Relations Officer","chk":"0","identifier":"56"},
{"id":"84","description":"Lead Artisan","chk":"0","identifier":"57"},
{"id":"85","description":"Lineworker","chk":"0","identifier":"58"},
{"id":"86","description":"Loss Control Assistant","chk":"0","identifier":"59"},
{"id":"87","description":"Loss Control Officer","chk":"0","identifier":"60"},
{"id":"88","description":"Loss Control Officer - Investigations","chk":"0","identifier":"0"},
{"id":"89","description":"Loss Control Officer - Operations","chk":"0","identifier":"0"},
{"id":"90","description":"Loss Controller","chk":"0","identifier":"61"},
{"id":"91","description":"Maintenance Engineer","chk":"0","identifier":"62"},
{"id":"92","description":"Marketing Officer","chk":"0","identifier":"63"},
{"id":"93","description":"Messenger","chk":"0","identifier":"64"},
{"id":"94","description":"Messenger - Cleaner","chk":"0","identifier":"0"},
{"id":"95","description":"Network Development Engineer","chk":"0","identifier":"65"},
{"id":"96","description":"Operations & Maintenance Engineer","chk":"0","identifier":"0"},
{"id":"97","description":"Panel Beater","chk":"0","identifier":"66"},
{"id":"98","description":"Personnel Clerk","chk":"0","identifier":"67"},
{"id":"99","description":"Personnel Officer","chk":"0","identifier":"68"},
{"id":"100","description":"Postgraduate Trainee","chk":"0","identifier":"69"},
{"id":"101","description":"Principal Technician","chk":"0","identifier":"70"},
{"id":"102","description":"Principal Technician - Drawing Office","chk":"0","identifier":"0"},
{"id":"103","description":"Principal Technician - Project Mgt","chk":"0","identifier":"0"},
{"id":"104","description":"Procurement Officer","chk":"0","identifier":"71"},
{"id":"105","description":"Revenue Assurance - Clerk","chk":"0","identifier":"0"},
{"id":"106","description":"Revenue Assurance Assistant","chk":"0","identifier":"72"},
{"id":"107","description":"Risk Officer","chk":"0","identifier":"73"},
{"id":"108","description":"Safety Health and Environment","chk":"0","identifier":"0"},
{"id":"109","description":"Sales Analyst","chk":"0","identifier":"74"},
{"id":"110","description":"Sales Executive","chk":"0","identifier":"75"},
{"id":"111","description":"Secretary","chk":"0","identifier":"76"},
{"id":"112","description":"Senior Accountant - FM","chk":"0","identifier":"0"},
{"id":"113","description":"Senior Accountant - MA","chk":"0","identifier":"0"},
{"id":"114","description":"Senior Client Services Officer","chk":"0","identifier":"79"},
{"id":"115","description":"Senior Engineer","chk":"0","identifier":"80"},
{"id":"116","description":"Senior Engineer - Operations and Maintenance","chk":"0","identifier":"81"},
{"id":"117","description":"Senior Engineer - Planning and Design","chk":"0","identifier":"82"},
{"id":"118","description":"Senior Engineer - Projects","chk":"0","identifier":"83"},
{"id":"119","description":"Senior Engineer- Operations","chk":"0","identifier":"0"},
{"id":"120","description":"Senior Foreperson","chk":"0","identifier":"84"},
{"id":"121","description":"Senior Foreperson - Mains","chk":"0","identifier":"0"},
{"id":"122","description":"Senior Foreperson - Substations","chk":"0","identifier":"0"},
{"id":"123","description":"Senior Loss Control Officer","chk":"0","identifier":"85"},
{"id":"124","description":"Senior System Controller","chk":"0","identifier":"0"},
{"id":"125","description":"Storekeeper","chk":"0","identifier":"86"},
{"id":"126","description":"Stores Assistant","chk":"0","identifier":"87"},
{"id":"127","description":"Stores Assistants","chk":"0","identifier":"0"},
{"id":"128","description":"Stores Clerk","chk":"0","identifier":"88"},
{"id":"129","description":"Stores Officer","chk":"0","identifier":"0"},
{"id":"130","description":"Supplies Officer","chk":"0","identifier":"0"},
{"id":"131","description":"Switchboard Operator","chk":"0","identifier":"89"},
{"id":"132","description":"Systems Administrator","chk":"0","identifier":"90"},
{"id":"133","description":"Systems Support Officer","chk":"0","identifier":"91"},
{"id":"134","description":"Technical Clerk","chk":"0","identifier":"92"},
{"id":"135","description":"Technician","chk":"0","identifier":"93"},
{"id":"136","description":"Technician - Drawing Office","chk":"0","identifier":"0"},
{"id":"137","description":"Technician - Energy","chk":"0","identifier":"0"},
{"id":"138","description":"Technician - Planning & Design","chk":"0","identifier":"0"},
{"id":"139","description":"Technician - Planning and Design","chk":"0","identifier":"94"},
{"id":"140","description":"Technician - Projects","chk":"0","identifier":"0"},
{"id":"141","description":"Technician - Substations","chk":"0","identifier":"0"},
{"id":"142","description":"Technician Assistant","chk":"0","identifier":"95"},
{"id":"143","description":"Technician Assistant - Substations","chk":"0","identifier":"0"},
{"id":"144","description":"Test","chk":"0","identifier":"96"},
{"id":"145","description":"Transport Controller","chk":"0","identifier":"97"},
{"id":"146","description":"Transport Officer","chk":"0","identifier":"98"},
{"id":"147","description":"worker","chk":"0","identifier":"0"},
{"id":"148","description":"Worker - Grounds","chk":"0","identifier":"0"}
]

ROLES = [
{"id":"5","role":"originator","name":"Auditor","description":"Role for the Auditor","application":"non_conformity"},
{"id":"4","role":"pay","name":"Payer","description":"Confirms the payment","application":"remittance_advice"},
{"id":"3","role":"authorise","name":"Authoriser","description":"Authorises the Remiitance Advice for Payment","application":"remittance_advice"},
{"id":"2","role":"check","name":"Checker","description":"Checks the Prepared Remittance Advice","application":"remittance_advice"},
{"id":"1","role":"prepare","name":"Requester","description":"Creates the Remittance advice Note","application":"remittance_advice"},
{"id":"6","role":"recipient","name":"Recipient","description":"Role for the recipeint of the Non Conformity","application":"non_conformity"},
{"id":"7","role":"supervisor","name":"Section Head\/ Customer Services Officer","description":"Normally the Section Head responsible for checking on the progress on NC raised on their subordinates","application":"non_conformity"},
{"id":"8","role":"create","name":"Requester","description":"Petty Cash Requester","application":"pettycash"},
{"id":"9","role":"approve","name":"Section Head \/ Customer Services Officer","description":"Section Head\/ Supervisor","application":"pettycash"},
{"id":"10","role":"disburse","name":"Cashier","description":"Role for disburing pettycash","application":"pettycash"},
{"id":"11","role":"create","name":"Requester","description":"Direct purchases requester","application":"adjudication"},
{"id":"12","role":"check","name":"Foreperson\/ Customer Services Officer","description":"Foreperson role for Checking a direct purchases request","application":"adjudication"},
{"id":"13","role":"process","name":"Procurement Officer","description":"Role for Procurement Officer","application":"adjudication"},
{"id":"14","role":"approve","name":"Section Head\/ District Manager","description":"Role for Section Head or District Manager","application":"adjudication"},
{"id":"15","role":"confirm","name":"Finance Manager","description":"Finance Manager Role","application":"adjudication"},
{"id":"16","role":"authorise","name":"General Manager","description":"General Manager role for Authorisation","application":"adjudication"},
{"id":"17","role":"create","name":"Requester","description":"Role for token Requester","application":"tokens"},
{"id":"18","role":"approve","name":"Section Head","description":"Role for token approver","application":"tokens"},
{"id":"19","role":"generation","name":"Revenue Officer","description":"Role for Revenue Officer responsible for Token Generation","application":"tokens"},
{"id":"20","role":"meter downloading","name":"Meter Downloading (Engineer)","description":"Role for Engineer responsible for meter downloading","application":"tokens"},
{"id":"21","role":"stores","name":"Stores Officer","description":"Role for Stores Officer for Reimbursement Tokens","application":"tokens"},
{"id":"22","role":"create","name":"Procurement Officer","description":"Role for Procurement Officer responsible for creating tender documents","application":"tenders"},
{"id":"23","role":"check","name":"Finance Manager","description":"Role for Finance Manager","application":"tenders"},
{"id":"24","role":"approve","name":"General Manager","description":"Role for General Manager","application":"tenders"},
{"id":"25","role":"request","name":"Requester","description":"Role for RFQ requester","application":"tenders"},
{"id":"26","role":"verify","name":"Foreperson\/ Customer Services Officer","description":"Role for the CSO\/Foreperson for verifying RFQ requests","application":"tenders"},
{"id":"27","role":"authorise","name":"Section Head\/ District Manager","description":"Role for Section Head\/ District Manager for Authorising RFQ requests","application":"tenders"},
{"id":"28","role":"create","name":"Requester","description":"Role for ACE requester","application":"ace"},
{"id":"29","role":"check","name":"Foreperson\/ Customer Services Officer","description":"Role for CSO\/Foreperson for checking ACE request","application":"ace"},
{"id":"30","role":"pass","name":"Section Head\/ District Manager","description":"Role for Section Head or District Manager","application":"ace"},
{"id":"31","role":"process","name":"Accounting Officer","description":"Role for Accounting Officer resposible for generating and attaching asset numbers to ACE`s.","application":"ace"},
{"id":"32","role":"sanction","name":"Finance Manager","description":"Role for Finance Manager","application":"ace"},
{"id":"33","role":"approve","name":"General Manager","description":"Role for General Manager","application":"ace"},
{"id":"34","role":"order","name":"Procurement Officer","description":"Role for Procurement Officer","application":"ace"},
{"id":"35","role":"authoriser","name":"Petty Cash Authoriser","description":"Petty Cash Authoriser","application":"pettycash"},
{"id":"36","role":"create","name":"Requester","description":"appraisal Requester","application":"appraisal"},
{"id":"37","role":"approve","name":"Section Head","description":"Section Head","application":"appraisal"},
{"id":"38","role":"reviewer","name":"reviewer","description":"Role for reviewing appraisal","application":"appraisal"},
{"id":"39","role":"hr","name":"hr","description":"Role for hr in appraisal","application":"appraisal"},
{"id":"40","role":"admin","name":"Administrator","description":"IT Administrator","application":"users"},
{"id":"41","role":"standard","name":"Standard","description":"Standard User","application":"users"},
{"id":"42","role":"create","name":"Procurement Officer","description":"Role for Procurement Officer responsible for creating Rfq documents","application":"purchase_request"},
{"id":"43","role":"check","name":"Finance Manager","description":"Role for Finance Manager","application":"purchase_request"},
{"id":"44","role":"approve","name":"General Manager","description":"Role for General Manager","application":"purchase_request"},
{"id":"45","role":"request","name":"Requester","description":"Role for RFQ requester","application":"purchase_request"},
{"id":"46","role":"authenticate","name":"Section head","description":"Role for RFQ Section head","application":"purchase_request"},
{"id":"47","role":"fore_person","name":"Fore Person","description":"View Depot Reports","application":"dashboards"},
{"id":"48","role":"section_head","name":"Section Head","description":"View Section Reports","application":"dashboards"},
{"id":"49","role":"district_manager","name":"District Manager","description":"View District Reports","application":"dashboards"},
{"id":"50","role":"executive","name":"Executive","description":"View Regional Reports","application":"dashboards"}
]

SECTIONS = [
{"id":"1","section":"GM Office","code":"521001","district_id":"","region_id":""},
{"id":"2","section":"Finance","code":"522001","district_id":"","region_id":""},
{"id":"3","section":"Stores","code":"522102","district_id":"","region_id":""},
{"id":"4","section":"Procurement","code":"522301","district_id":"","region_id":""},
{"id":"5","section":"Human Resource","code":"523001","district_id":"","region_id":""},
{"id":"6","section":"Engineering","code":"524001","district_id":"","region_id":""},
{"id":"7","section":"Network Development","code":"524101","district_id":"","region_id":""},
{"id":"8","section":"Transport","code":"524202","district_id":"","region_id":""},
{"id":"9","section":"Operations and Maintenance","code":"524301","district_id":"","region_id":""},
{"id":"10","section":"Commercial","code":"525000","district_id":"","region_id":""},
{"id":"11","section":"Risk Management","code":"526001","district_id":"","region_id":""},
{"id":"12","section":"Information Technology","code":"527001","district_id":"","region_id":""},
{"id":"13","section":"Mabelreign Depot","code":"524503","district_id":"2","region_id":"1"},
{"id":"14","section":"Borrowdale Depot","code":"524703","district_id":"4","region_id":"1"},
{"id":"15","section":"Glen View Depot","code":"524602","district_id":"3","region_id":"1"},
{"id":"16","section":"Kuwadzana Depot","code":"524502","district_id":"2","region_id":"1"},
{"id":"17","section":"Mabvuku Depot","code":"524704","district_id":"4","region_id":"1"},
{"id":"18","section":"Ruwa Depot","code":"524705","district_id":"4","region_id":"1"},
{"id":"19","section":"Southerton Depot","code":"524604","district_id":"3","region_id":"1"},
{"id":"20","section":"Warren Park Depot","code":"524504","district_id":"2","region_id":"1"},
{"id":"21","section":"Waterfalls Depot","code":"524603","district_id":"3","region_id":"1"},
{"id":"22","section":"CBD Depot","code":"524702","district_id":"4","region_id":"1"},
{"id":"23","section":"Makoni Depot","code":"524402","district_id":"1","region_id":"1"},
{"id":"24","section":"Zengeza Depot","code":"524403","district_id":"1","region_id":"1"},
{"id":"25","section":"Seke","code":"000000","district_id":"1","region_id":"1"}
]