from django.urls import path

from . import views

urlpatterns = [
    path('create', views.create, name='user_manual_create'),
    path('view_files', views.view_files, name='user_manual_index'),
    path('download_file', views.download_file, name='download_file'),
    path('edit_file/<str:file_id>', views.edit_file, name='user_manual_edit_file'),
    path('view_myfiles', views.view_by_category, name='user_manual_view_files'),
    path('get-files/<int:file_type_id>/', views.get_files, name='get_files'),
    path('get-cat2/<int:file_type>/<int:selected_cat>', views.get_cat2, name='get_cat2'),
    path('view_legislation', views.view_legislation, name='user_manual_view_legislation'),
    path('view_firstview', views.view_firstview, name='user_manual_view_advanced'),
    path('view_policies', views.view_policies, name='user_manual_view_policies'),
    path('view_index', views.view_index, name='user_manual_view_index'),
    path('view_1_10', views.view_1_10, name='user_manual_view_1_10'),
    path('view_11_20', views.view_11_20, name='user_manual_view_11_20'),
    path('view_21_30', views.view_21_30, name='user_manual_view_21_30'),
    path('view_31_45', views.view_31_45, name='user_manual_view_31_45'),
    path('view_user_manuals', views.view_user_manuals, name='user_manual_view_user_manuals'),
    path('view_eng_manuals', views.view_eng_manuals, name='user_manual_view_eng_manuals'),
    path('view_drawings', views.view_drawings, name='user_manual_view_drawings'),
    path('view_knowledge_base', views.view_knowledge_base, name='user_manual_knowledge_base'),
    path('view_com_base', views.view_com_base, name='user_manual_com_base'),
    path('view_eng_base', views.view_eng_base, name='user_manual_eng_base'),
    path('view_ict_base', views.view_ict_base, name='user_manual_ict_base'),
    path('test', views.test, name='user_manual_test'),

    
    path('view_legislation/ea', views.view_ea, name='view_ea'),
    path('view_legislation/gl', views.view_gl, name='view_gl'),
    path('view_legislation/si', views.view_si, name='view_si'),
    path('view_legislation/policies/commercial', views.view_commercial_policies, name='view_commercial_policies'),
    path('view_legislation/policies/hr', views.view_hr_policies, name='view_hr_policies'),
    path('view_legislation/engineering', views.view_engineering, name='view_engineering'),
    path('view_legislation/policies/finance', views.view_finance_policies, name='view_finance_policies'),
    path('view_legislation/policies/ict', views.view_ict_policies, name='view_ict_policies'),
    path('view_legislation/policies/risk', views.view_risk_policies, name='view_risk_policies'),
    path('view_legislation/reports', views.view_reports, name='view_reports'),
    path('view_legislation/protection', views.view_protection, name='view_protection'),
    path('view_legislation/earthing', views.view_earthing, name='view_earthing'),
    path('view_legislation/transformers', views.view_transformers, name='view_transformers'),
    path('view_legislation/fuses', views.view_fuses, name='view_fuses'),
    path('view_legislation/imm', views.view_imm, name='view_imm'),
    path('view_legislation/tg', views.view_tg, name='view_tg'),
    path('view_legislation/switchgear', views.view_switchgear, name='view_switchgear'),
    path('view_legislation/por', views.view_por, name='view_por'),
    path('view_legislation/io', views.view_io, name='view_io'),
    path('view_legislation/clearance', views.view_clearance, name='view_clearance'),
    path('view_legislation/mines', views.view_mines, name='view_mines'),
    path('view_legislation/supplies', views.view_supplies, name='view_supplies'),
    path('view_legislation/samples', views.view_samples, name='view_samples'),
    path('view_legislation/cables', views.view_cables, name='view_cables'),
    path('view_legislation/capital', views.view_capital, name='view_capital'),
    path('view_legislation/government', views.view_government, name='view_government'),
    path('view_legislation/phases', views.view_phases, name='view_phases'),
    path('view_legislation/insulators', views.view_insulators, name='view_insulators'),
    path('view_legislation/locks', views.view_locks, name='view_locks'),
    path('view_legislation/rmasts', views.view_rmasts, name='view_rmasts'),
    path('view_legislation/substations', views.view_substations, name='view_substations'),
    path('view_legislation/fire', views.view_fire, name='view_fire'),
    path('view_legislation/defective', views.view_defective, name='view_defective'),
    path('view_legislation/services', views.view_services, name='view_services'),
    path('view_legislation/consumers', views.view_consumers, name='view_consumers'),
    path('view_legislation/lifting', views.view_lifting, name='view_lifting'),
    path('view_legislation/transport', views.view_transport, name='view_transport'),
    path('view_legislation/lpa', views.view_lpa, name='view_lpa'),
    path('view_legislation/insulation', views.view_insulation, name='view_insulation'),
    path('view_legislation/cables', views.view_cables, name='view_cables'),
    path('view_legislation/capacitors', views.view_capacitors, name='view_capacitors'),
    path('view_legislation/explosive', views.view_explosive, name='view_explosive'),
    path('view_legislation/standard', views.view_standard, name='view_standard'),
    path('view_legislation/cradles', views.view_cradles, name='view_cradles'),
    path('view_legislation/11kv', views.view_11kv, name='view_11kv'),
    path('view_legislation/conductors', views.view_conductors, name='view_contuctors'),
    path('view_legislation/roads', views.view_roads, name='view_roads'),
    path('view_legislation/zetdc', views.view_zetdc, name='view_zetdc'),
    path('view_legislation/power', views.view_power, name='view_power'),
    path('view_legislation/substation', views.view_substation, name='view_substation'),
    path('view_legislation/safety', views.view_safety, name='view_safety'),
    path('view_legislation/lighting', views.view_lighting, name='view_lighting'),
    path('view_legislation/capacity', views.view_capacity, name='view_capacity'),
    path('view_legislation/procurement', views.view_procurement, name='view_procurement'),
    path('view_legislation/publications', views.view_publications, name='view_publications'),
    path('view_legislation/external_docs', views.view_external_docs, name='view_external_docs'),
    path('view_legislation/drone_tech', views.view_drone_tech, name='view_drone_tech'),

    path('view_legislation/user_manuals/commercial', views.view_commercial_usermanuals, name='view_commercial_usermanuals'),
    path('view_legislation/user_manuals/hr', views.view_hr_usermanuals, name='view_hr_usermanuals'),
    path('view_legislation/user_manuals/finance', views.view_finance_usermanuals, name='view_finance_usermanuals'),
    path('view_legislation/user_manuals/ict', views.view_ict_usermanuals, name='view_ict_usermanuals'),
    path('view_legislation/user_manuals/risk', views.view_risk_usermanuals, name='view_risk_usermanuals'),
    path('view_legislation/switchgear', views.view_switchgear, name='view_switchgear'),
    path('view_legislation/dtech', views.view_dtech, name='view_dtech'),
    path('view_legislation/ndm', views.view_ndm, name='view_ndm'),
    path('view_legislation/gis', views.view_gis, name='view_gis'),
    path('view_legislation/itrack', views.view_itrack, name='view_itrack'),
    path('view_legislation/sap', views.view_sap, name='view_sap'),
    path('view_legislation/oms', views.view_oms, name='view_oms'),
    path('view_legislation/drawing', views.view_drawing, name='view_drawing'),
    path('view_legislation/standards', views.view_standards, name='view_standards'),
    path('view_legislation/specifications', views.view_specifications, name='view_specifications'),
    path('view_legislation/risk_management', views.view_risk_management, name='view_risk_management'),
    path('view_legislation/communication_management', views.view_communication_management, name='view_communication_management'),
    path('view_legislation/quality_management', views.view_quality_management, name='view_quality_management'),
    path('view_legislation/configuration_management', views.view_configuration_management, name='view_configuration_management'),
    path('view_legislation/risk_register', views.view_risk_register, name='view_risk_register'),
    path('view_legislation/lessons_learnt', views.view_lessons_learnt, name='view_lessons_learnt'),
    path('view_legislation/quality_register', views.view_quality_register, name='view_quality_register'),
    path('view_legislation/configuration_item', views.view_configuration_item, name='view_configuration_item'),
    path('view_legislation/current_projects', views.view_current_projects, name='view_current_projects'),
    

    path('search', views.file_search, name='file_search'),

     
]

